# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import experiment_command_pb2 as experiment__command__pb2
import streaming_signals_pb2 as streaming__signals__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0csdk_services\x1a\x18\x65xperiment_command.proto\x1a\x17streaming_signals.proto\"\x07\n\x05\x45mpty2\xcb\x01\n\x11\x45xperimentService\x12P\n\x0cWatchSignals\x12\x13.sdk_services.Empty\x1a).sdk_streaming_signals.W_TrainingStatusEx0\x01\x12\x64\n\x11\x45xperimentCommand\x12&.sdk_experiment_command.TrainerCommand\x1a\'.sdk_experiment_command.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=83
  _globals['_EMPTY']._serialized_end=90
  _globals['_EXPERIMENTSERVICE']._serialized_start=93
  _globals['_EXPERIMENTSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
