# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import experiment_command_pb2 as experiment__command__pb2
import services_pb2 as services__pb2
import streaming_signals_pb2 as streaming__signals__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExperimentServiceStub(object):
    """Interface to communicate btw UI and SDK
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchSignals = channel.unary_stream(
                '/sdk_services.ExperimentService/WatchSignals',
                request_serializer=services__pb2.Empty.SerializeToString,
                response_deserializer=streaming__signals__pb2.W_TrainingStatusEx.FromString,
                _registered_method=True)
        self.ExperimentCommand = channel.unary_unary(
                '/sdk_services.ExperimentService/ExperimentCommand',
                request_serializer=experiment__command__pb2.TrainerCommand.SerializeToString,
                response_deserializer=experiment__command__pb2.CommandResponse.FromString,
                _registered_method=True)


class ExperimentServiceServicer(object):
    """Interface to communicate btw UI and SDK
    """

    def WatchSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExperimentCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExperimentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchSignals': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSignals,
                    request_deserializer=services__pb2.Empty.FromString,
                    response_serializer=streaming__signals__pb2.W_TrainingStatusEx.SerializeToString,
            ),
            'ExperimentCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExperimentCommand,
                    request_deserializer=experiment__command__pb2.TrainerCommand.FromString,
                    response_serializer=experiment__command__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdk_services.ExperimentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdk_services.ExperimentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExperimentService(object):
    """Interface to communicate btw UI and SDK
    """

    @staticmethod
    def WatchSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sdk_services.ExperimentService/WatchSignals',
            services__pb2.Empty.SerializeToString,
            streaming__signals__pb2.W_TrainingStatusEx.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExperimentCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdk_services.ExperimentService/ExperimentCommand',
            experiment__command__pb2.TrainerCommand.SerializeToString,
            experiment__command__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
