# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming_signals.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'streaming_signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17streaming_signals.proto\x12\x15sdk_streaming_signals\",\n\rMetricsStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\x9a\x01\n\x10\x41nnotationStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12G\n\x08metadata\x18\x02 \x03(\x0b\x32\x35.sdk_streaming_signals.AnnotationStatus.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xc7\x02\n\x12W_TrainingStatusEx\x12\x16\n\ttimestamp\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0f\x65xperiment_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tmodel_age\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x41\n\x0emetrics_status\x18\x04 \x01(\x0b\x32$.sdk_streaming_signals.MetricsStatusH\x03\x88\x01\x01\x12G\n\x11\x61nnotation_status\x18\x05 \x01(\x0b\x32\'.sdk_streaming_signals.AnnotationStatusH\x04\x88\x01\x01\x42\x0c\n\n_timestampB\x12\n\x10_experiment_nameB\x0c\n\n_model_ageB\x11\n\x0f_metrics_statusB\x14\n\x12_annotation_statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANNOTATIONSTATUS_METADATAENTRY']._loaded_options = None
  _globals['_ANNOTATIONSTATUS_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_METRICSSTATUS']._serialized_start=50
  _globals['_METRICSSTATUS']._serialized_end=94
  _globals['_ANNOTATIONSTATUS']._serialized_start=97
  _globals['_ANNOTATIONSTATUS']._serialized_end=251
  _globals['_ANNOTATIONSTATUS_METADATAENTRY']._serialized_start=204
  _globals['_ANNOTATIONSTATUS_METADATAENTRY']._serialized_end=251
  _globals['_W_TRAININGSTATUSEX']._serialized_start=254
  _globals['_W_TRAININGSTATUSEX']._serialized_end=581
# @@protoc_insertion_point(module_scope)
