# Global configuration
device: auto
experiment_name: det_YOLO_usecase
training_steps_to_do: null  # Set to null for infinite training until manually stopped
root_log_dir: .  # Empty to write in tmp directory, or specify a path to store logs and checkpoints

# Checkppoint Manager
checkpoint_manager:
  load_config: true  
  load_data: true
  load_model: true 

# Model config.
model:
  name: yolo11s.pt
  lr: 0.001
  momentum: 0.9

# Initially compute natural sorting values, e.g., average intensity. More details in the README.md file.
compute_natural_sort: true

# Experiment parameters
eval_full_to_train_steps_ratio: 128
experiment_dump_to_train_steps_ratio: 128
tqdm_display: true
is_training: false  # Start training immediately or not

# Serving
serving_grpc: true
serving_cli: false

# Configure global dataframe storage
ledger_enable_flushing_threads: true
ledger_enable_h5_persistence: true
ledger_flush_max_rows: 5000
ledger_flush_interval: 60.0

# Data
num_classes: 2
image_size: 1024
data_root: /home/rotaru/Desktop/GRAYBOX/datasets/TrespassColor.v6i.yolov8/data.yaml
data:
  train_loader:
    batch_size: 4
    shuffle: true
  test_loader:
    batch_size: 2
    shuffle: false
