# Global configuration
device: auto
experiment_name: det_YOLO_usecase
training_steps_to_do: null  # Set to null for infinite training until manually stopped
# root_log_dir:  # Empty to write in tmp directory, or specify a path to store logs and checkpoints

# Checkppoint Manager
checkpoint_manager:
  load_config: true  # Disable loading previous checkpoint configuration to allow for changes in the current config.yaml file
  load_data: true  # Disable loading previous checkpoint data to allow for changes in the current config.yaml file
  load_model: true  # Disable loading previous checkpoint model weights and archi. to allow for changes in the current config.yaml file

# Model config.
model:
  name: yolo11s.pt
  lr: 0.01
  momentum: 0.9

# Initially compute natural sorting values, e.g., average intensity. More details in the README.md file.
compute_natural_sort: true

# Experiment parameters
eval_full_to_train_steps_ratio: 5
experiment_dump_to_train_steps_ratio: 5
tqdm_display: true
is_training: false  # Start training immediately or not

# Serving
serving_grpc: true
serving_cli: false

# Configure global dataframe storage
ledger_enable_flushing_threads: true
ledger_enable_h5_persistence: false
ledger_flush_max_rows: 5000
ledger_flush_interval: 60.0

# Data
num_classes: 2
image_size: 320
data_root: ..\data\data.yaml
data:
  train_loader:
    batch_size: 4
    shuffle: true
  test_loader:
    batch_size: 2
    shuffle: false
