import unittest
import tempfile
import grpc
import sys
import os
# Make sure to set up your environment so these imports work
# You may need to replace 'your_project_pb2' and 'your_project_pb2_grpc'
# with the actual names generated by protoc.
try:
    # Assuming the generated files are accessible
    sys.path.append(os.path.join(os.path.dirname(os.path.dirname(__file__)), "stubs"))
    from weightslab.stubs import services_pb2 as pb2
    from weightslab.stubs import services_pb2_grpc as pb2_grpc
except ImportError:
    print("Error: Protobuf generated files (pb2, pb2_grpc) not found.")
    print("Please ensure you have run the protoc compiler successfully.")
    sys.exit(1)

from torch import optim
from torchmetrics import Accuracy

from torchvision import transforms as T
from torchvision import datasets as ds

from weightslab.experiment.experiment import Experiment
from weightslab.tests.torch_models import FashionCNN

from threading import Thread


# --- Configuration ---
SERVER_ADDRESS = 'localhost:50051'
TIMEOUT_SECONDS = 5  # Timeout for connection and streaming response

# clear && rm -r ./stubs && mkdir -p ./stubs && touch ./stubs/__init__.py && python -m grpc_tools.protoc -Iproto/ --python_out=./stubs/ --grpc_python_out=./stubs/ ./proto/*.proto


# --- gRPC Client ---
def init_gRPC_Client():
    """
        Run a toy experiment on MNIST.
    """
    from weightslab.experiment.trainer_worker import serve

    # Run the experiment
    print("\n--- Hello World ---\n")

    # Init Variables
    temporary_directory = tempfile.mkdtemp()

    # Instanciate the model
    model = FashionCNN()

    # Dataset initialization
    data_eval = ds.MNIST(
        os.path.join(temporary_directory, "data"),
        download=True,
        train=False,
        transform=T.Compose([T.ToTensor()])
    )
    data_train = ds.MNIST(
        os.path.join(temporary_directory, "data"),
        train=True,
        transform=T.Compose([T.ToTensor()]),
        download=True
    )

    # Init Experiment
    experiment = Experiment(
        model=model,
        optimizer_class=optim.Adam,
        train_dataset=data_train,
        metrics={
            'acc': Accuracy(task="multiclass", num_classes=10)
        },
        input_shape=model.input_shape,
        eval_dataset=data_eval,
        device='cpu',
        learning_rate=1e-2,
        batch_size=128,
        training_steps_to_do=1e6,
        experiment_dump_to_train_steps_ratio=1e9,
        name="MNIST Training & Testing",
        root_log_dir=temporary_directory,
        train_shuffle=True
    )
    experiment.set_is_training(False)

    def training_thread_callback():
        n = 0
        while True:
            if experiment.get_is_training():
                print(f'Training one step further.. {n}')
                experiment.train_step_or_eval_full()
                eval_loss, eval_accuracy = experiment.eval_n_steps(32)
                print(f'Eval loss: {eval_loss}, Eval accuracy: {eval_accuracy}')
                n += 1

    training_thread = Thread(target=training_thread_callback)
    training_thread.start()

    # Service server
    serve()


def init_pb2_client(cls):
    # 0. Init the experiment
    # TODO (GP): ... Make exp launch here in another thread

    # 1. Create the Channel
    cls.channel = grpc.insecure_channel(
        SERVER_ADDRESS,
        options=[('grpc.max_receive_message_length', 32 * 1024 * 1024)]
    )
    cls.stub = pb2_grpc.ExperimentServiceStub(cls.channel)

    # 2. Check for server availability
    try:
        # Wait for the channel to become ready, up to the timeout
        grpc.channel_ready_future(cls.channel).result(timeout=TIMEOUT_SECONDS)
        print("Channel established successfully.")
    except grpc.FutureTimeoutError:
        # If the server is not ready, skip all tests in this class
        cls.server_ready = False
        cls.server_error = f"Server at {SERVER_ADDRESS} is UNAVAILABLE."
        print(f"Connection failed: {cls.server_error}")
    else:
        cls.server_ready = True
        cls.server_error = None

    return cls


class TestExperimentServiceIntegration(unittest.TestCase):
    """
    Tests the client-side integration with the ExperimentService gRPC server.
    """

    @classmethod
    def setUpClass(cls):
        """
        Setup a single gRPC channel instance for all tests in this class.
        """
        print(f"\nSetting up gRPC channel to {SERVER_ADDRESS}...")

        # Init client
        cls = init_pb2_client(cls)

    @classmethod
    def tearDownClass(cls):
        """
        Clean up resources by closing the gRPC channel.
        """
        if cls.server_ready:
            cls.channel.close()
            print("\ngRPC channel closed.")

    def test_watch_signals(self):
        """
        Tests the streaming RPC WatchSignals to ensure a valid response is received.
        """
        if not self.server_ready:
            # Skip the test if the setup failed to connect to the server
            self.skipTest(self.server_error)
            return

        print("\n--- Running WatchSignals Test ---")

        # Prepare for the streaming call
        request = pb2.Empty()  # Assuming WatchSignals takes an Empty message
        response_received = False

        try:
            # Set a timeout for the streaming call itself
            response_iterator = self.stub.WatchSignals(request, timeout=TIMEOUT_SECONDS)

            # Iterate through the streaming response until a valid signal is found
            for response in response_iterator:
                # 3. Validation Checks

                # Check if the response object has the expected fields
                self.assertTrue(hasattr(response, 'model_age'), 
                                "Response object is missing 'model_age' field.")
                self.assertTrue(hasattr(response, 'experiment_name'), 
                                "Response object is missing 'experiment_name' field.")

                # Further check if the required fields are non-empty/non-zero
                self.assertNotEqual(response.experiment_name, "", 
                                    "Experiment name should not be empty.")

                response_received = True
                print(f"Received valid signal: Exp={response.experiment_name}, Age={response.model_age}")

                # Once a valid signal is received, we can stop the stream for the test
                break

        except grpc.RpcError as e:
            # Specifically handle RPC errors during the streaming call
            self.fail(f"RPC Call failed with code {e.code().name}: {e.details()}")

        except Exception as e:
            self.fail(f"An unexpected error occurred during the RPC stream: {e}")

        # Final assertion to ensure the loop actually received a response
        self.assertTrue(response_received,
                        "The WatchSignals stream did not yield any response within the timeout.")

    def test_request_experiment_command(self):
        """
            Tests the streaming RPC RequestExperimentCommand to ensure a valid response is received.
        """
        if not self.server_ready:
            # Skip the test if the setup failed to connect to the server
            self.skipTest(self.server_error)
            return

        # Get Initial state response for both train and eval commands.
        request_initial_state_train = pb2.experiment__command__pb2 \
            .ExperimentCommand(
                get_hyper_parameters=True,
                get_interactive_layers=True,
                get_data_records="train",
            )
        request_initial_state_eval = pb2.experiment__command__pb2 \
            .ExperimentCommand(
                get_hyper_parameters=True,
                get_interactive_layers=True,
                get_data_records="train",
            )
        try:
            # Train
            initial_state_response_train = self.stub.WatchOrEditExperiment(
                request_initial_state_train
            )
            print(f'Initial state response: {initial_state_response_train}')

            # Eval
            initial_state_response_eval = self.stub.WatchOrEditExperiment(
                request_initial_state_eval
            )
            print(f'Initial state response: {initial_state_response_eval}')
        except grpc.RpcError as e:
            # Specifically handle RPC errors during the streaming call
            self.fail(
                f"RPC Call failed with code {e.code().name}: {e.details()}"
            )
        except Exception as e:
            self.fail(
                f"An unexpected error occurred during the RPC stream: {e}"
            )

        # Modify Hyperparameters and launch experiment
        hyper_parameter = pb2.experiment__command__pb2.HyperParameters()
        hyper_parameter.training_steps_to_do = 100  # >0 launch the exp.
        hyper_parameter.experiment_name = "unittest exp"
        hyper_parameter.learning_rate = 1e-7
        hyper_parameter.batch_size = 4
        hyper_parameter.is_training = True  # Launch the pending experiment
        hyper_parameter.full_eval_frequency = 256
        hyper_parameter.checkpont_frequency = 512
        request = pb2.experiment__command__pb2.ExperimentCommand(
            hyper_parameter_change=pb2.experiment__command__pb2
            .HyperParameterCommand(
                hyper_parameters=hyper_parameter
            )
        )
        self.stub.WatchOrEditExperiment(request)

        # Reach
        print("Fetched initial state.")

    def test_watch_or_edit_computational_graph(self):
        """
        Tests the RPC WatchOrEditComputationalGraph to ensure a valid response
        is received.
        """
        if not self.server_ready:
            # Skip the test if the setup failed to connect to the server
            self.skipTest(self.server_error)
            return
        # - Get layers (nodes): Request the layers of the graph to be plot.

        # - Get dependencies (edges): Request the dependencies of the graph.

        # - Get weights (node's data): Request the weights of a node.

        # - Get activation (node's data): Request the activation map of a node.

        # - ManipulateWeights: Operate on layer's weights.
            # - Add neurons: Add a new neuron to a layer.

            # - Prune neurons: Remove a neuron from a layer.

            # - Freeze neurons: Freeze weights.

            # - Reset neurons: Reset weights.


# To run this test file directly:
if __name__ == '__main__':
    # Create a test suite
    suite = unittest.TestSuite()
    # suite.addTest(TestExperimentServiceIntegration('test_request_experiment_command'))
    # suite.addTest(TestExperimentServiceIntegration('test_watch_signals'))
    suite.addTest(TestExperimentServiceIntegration('test_watch_or_edit_computational_graph'))

    # Run ordered tests
    runner = unittest.TextTestRunner()
    runner.run(suite)
